-- AlterTable
ALTER TABLE "favorite_pokemon"
ADD COLUMN "name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "imageUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "type" TEXT NOT NULL DEFAULT '',
ADD COLUMN "abilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "favorite_pokemon"
ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "imageUrl" DROP DEFAULT,
ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "abilities" DROP DEFAULT;
